name: Test CMake app

on:
    push:
        paths:
            - "**.cpp"
            - "**.h"
            - "CMakeLists.txt"
            - "**.cmake"
    pull_request:
        paths:
            - "**.cpp"
            - "**.h"
            - "CMakeLists.txt"
            - "**.cmake"

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: |
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -S . -G "MinGW Makefiles"
          else
            cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -S .
          fi

    - name: Build
      run: cmake --build build --config ${{env.BUILD_TYPE}}
      
    - name: Run app
      run: 	./build/swirl
